_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "./pretrained_backbone/vitaev2_s_convert.pth"
  TRANSFORMER:
    VOC_SIZE: 5462
  
DATASETS:
  TRAIN: ("chnsyn_train", "rects_train", "rects_val", "lsvt_train", "art_train",)
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-4
  WARMUP_ITERS: 0
  STEPS: (300000,)
  MAX_ITER: 400000
  CHECKPOINT_PERIOD: 300000

TEST:
  EVAL_PERIOD: 100000000

OUTPUT_DIR: "output/vitaev2_s/rects/pretrain"
