_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "pretrained_backbone/R-101.pkl"
  
DATASETS:
  TRAIN: ("syntext1","syntext2","totaltext_train","mlt","ic13_train","ic15_train",)
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (320000,)
  MAX_ITER: 375000
  CHECKPOINT_PERIOD: 100000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "output/R101/150k_tt_mlt_13_15/pretrain"